// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assessment_sinar_tambang.Data;

#nullable disable

namespace assessment_sinar_tambang.Migrations
{
    [DbContext(typeof(MvcBuilder))]
    partial class MvcBuilderModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("assessment_sinar_tambang.Models.DataTables.Dosen", b =>
                {
                    b.Property<string>("Nip")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nama_Dosen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nip");

                    b.ToTable("dosen");
                });

            modelBuilder.Entity("assessment_sinar_tambang.Models.DataTables.Matakuliah", b =>
                {
                    b.Property<string>("Kode_MK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nama_MK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SKS")
                        .HasColumnType("bigint");

                    b.HasKey("Kode_MK");

                    b.ToTable("matakuliah");
                });
#pragma warning restore 612, 618
        }
    }
}
